var token = 'EAAFImZANBBWwBAGrV9Ovpf4ZCEXhqBVPL2MZCgBq3ZCDngEMssWZBL1010IfBqdztIXgdvDy8Tstcj5J5lKzQUZAwTmzvpZAZBQyZAPALU25q7j5TltyzZAs5PIyJkwxlaC95TUQDIevwU2PlqLQYm9p0dpvI9npIlnEGO9LA9hjNdIlBdsinBwMlU7GqZBmRAujcQiyk47lbyuuwZDZD'

exports.urls = 'https://graph.facebook.com/v5.0/me?fields=id,name,feed&access_token=' + token